### ISSUE TITLE
Online mode bypass

### ISSUE THREAD

**Issue by w3bb** [Additional-Mods/simplerauth#11]
If a user is authenticated with Mojang's servers, they should be able to skip logging in.

**Comment by Dqu1J** [comment]
This feature is implemented and will be added in 1.2.0 release!

**Comment by w3bb** [comment]
Awesome :D

**Comment by w3bb** [comment]
Will this require the server to be in online mode? Will this mess with the UUIDs of an existing offline player?

**Comment by Dqu1J** [comment]
> Will this require the server to be in online mode? Will this mess with the UUIDs of an existing offline player?

Nope. Server can be either in online, or offline mode. No additional setup will be needed, only updating the mod!

**Comment by w3bb** [comment]
Awesome, thanks

**Comment by Dqu1J** [comment]
1.2.0 is now released!
