### ISSUE TITLE
Goodmod 

### ISSUE THREAD

**Issue by AlexVin-Dev** [Additional-Mods/simplerauth#17]
**Describe the error**
With automatic authorization, Godmode is issued

**For Playback**
1. Log in.
2. Exit the game.
3. Connect again.

**Expected behavior**
Immortality should not be given out
**Screenshots**
![image](https://user-images.githubusercontent.com/15629077/125602888-a4c753d9-e96d-401c-ad1b-4e6588d0d489.png)

**Version**
Mod version: 1.2.0 
Minecraft version: 1.17.1
Fabric Version: 0.7.4

**Comment by IotaBread** [comment]
Has been fixed in 1.2.1-pre1 with commit e36861acb56f8569b34a397846f3ac8bc26e8907
