### ISSUE TITLE
Mobs wont go aggro and no fall damage

### ISSUE THREAD

**Issue by AchalS-iglu** [Additional-Mods/simplerauth#20]
Mobs wont go aggro and no fall damage

**Comment by AchalS-iglu** [comment]
Okay so after a little bit of testing, I removed the mod, I was still invisible and invulnerable then I did /kill on myself and it was fixed. now I cannot /kill the entire server that'd be wrong how do I remove the invisible and invulnerable from everyone?

**Comment by Dqu1J** [comment]
Please, send your mod version, fabric loader version and Minecraft version.

**Comment by Dqu1J** [comment]
No necessary information was provided. Unable to reproduce on the latest version (1.2.1) on both 1.16.5 and 1.17.1. Closing this issue now.

**Comment by Dqu1J** [comment]
If you were using 1.2.0, please update to 1.2.1, as this issue was fixed in 1.2.1.
1.2.1 is now released both on 1.17 and 1.16.5
If you still experience this issue on 1.2.1 - create a new issue or reopen this one.
Please, provide as much information as you can.

**Comment by AchalS-iglu** [comment]
I did, the update came out legit an hour after I downlaoded 1.2.0, THANKS!
