### ISSUE TITLE
Unauthenticated players send too many packets per second

### ISSUE THREAD

**Issue by Londiuh** [Additional-Mods/simplerauth#32]
**Describe the bug**
Unauthenticated players send too many packets. This may be caused by the constant teleport to freeze the player. This is annoying for servers with rate limit. Normal gameplay doesn't exceed 800 packets/sec and unauthenticated players can easily exceed 1500 packets/sec (even if not moving)

**Expected behavior**
Unauthenticated players send the same amount of packets per second than authenticated players

**Version**
Mod version: 1.3.0
Minecraft version: 1.17.1
Fabric version: 0.7.4

**Comment by Dqu1J** [comment]
Can you please see if that happens on 681f90b ?

**Comment by Londiuh** [comment]
Nice, no more rate limit kicks (I have rate limit in 800 packets/sec).

But now console spams this:
```log
[22:58:50] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
```
Also if you're in air you sometimes fall 1 block.

**Comment by Dqu1J** [comment]
Closing this now. Console spam is #35
