### ISSUE TITLE
Invulnerability in survival

### ISSUE THREAD

**Issue by Londiuh** [Additional-Mods/simplerauth#33]
**Describe the bug**
Invulnerability still enabled when switching your gamemode from creative to survival or adventure.

**To Reproduce**
- Join with creative mode
- Login
- Change your gamemode to survival or adventure

**Expected behavior**
You don't have invulnerability in survival & adventure

**Version**
Mod version: 1.3.0
Minecraft version: 1.17.1
Fabric version: 0.7.4

**Comment by Dqu1J** [comment]
Invulnerability again? Will test that soon.

**Comment by Londiuh** [comment]
Seems that creative now has its own invulnerability and is independent of `invulnerable`. Maybe since 1.17?
