### ISSUE TITLE
Publish on JitPack or GitHub Packages 

### ISSUE THREAD

**Issue by Londiuh** [Additional-Mods/simplerauth#37]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Now with the auth events coming to 1.4.0 you need to add simplerauth as a dependency to your mod. So it would be cool to publish on JitPack or GitHub Packages. Instead of adding the dependency from a local file.

**Version**
Mod version: 1.4.0
Minecraft version: 1.17.1

**Comment by Dqu1J** [comment]
The [1.4.0-rc1](https://github.com/Dqu1J/simplerauth/packages/1043482?version=1.4.0-rc1) has been published on Github Packages.
