### ISSUE TITLE
Passwords are not hashed

### ISSUE THREAD

**Issue by MxOrbulent** [Additional-Mods/simplerauth#4]
**Is your feature request related to a problem? Please describe.**
Passwords are saved in clean text. This is a massive problem for anything regarding authentication.

**Describe the solution you'd like**
Add encryption to passwords. Saving in clear text is a big no no. Remember the PSN hack that occoured 2011.

**Describe alternatives you've considered**
???? I do not understand what you mean

**Additional context**
Take a look at this:
https://www.javainterviewpoint.com/java-salted-password-hashing/

**Version**
Mod version: SimplerAuth-1.1.1
Minecraft version:  1.17
Fabric version: fabric-api-0.35.1+1.17

**Comment by MxOrbulent** [comment]
Saw that he intends to hash passwords. Good!
Just don't forget to salt them too. :)
I will be closing this issue.
https://github.com/Dqu1J/simplerauth/projects/2#card-63423615

**Comment by Dqu1J** [comment]
I decided to add that sooner, so it is already implemented and will be released with 1.1.2!
15600e5

**Comment by Tommimon** [comment]
Hi, any clue of when 1.1.2 will come out?

I don't want to have password saved in plain text. I tried to compile most recent commit by my myself with `./gradlew buld` but I got an error.

Gradle version: 7.0.2
Java Version: 16

**Comment by Dqu1J** [comment]
1.1.2 Will most likely come out in the next 24 hours! You can use the latest Github Actions build if you are unable to compile.

**Comment by Tommimon** [comment]
Nice! I can wait one day, thanks a lot for your work.

Last question: where are password hashes stored? How can i find them?

**Comment by Dqu1J** [comment]
The database is in config folder. It should be named “simplerauth-database.json” if I remember correctly. @Tommimon

**Comment by Dqu1J** [comment]
v1.1.2 is now released! That was quicker than I estimated.
If you have used the build with hashed passwords, you will need to reset your database file. If you used v1.1.1 or older, then you're good.
