### ISSUE TITLE
1.18 

### ISSUE THREAD

**Issue by PortableGames** [Additional-Mods/simplerauth#40]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Version**
Mod version: 
Minecraft version: 
Fabric version:

**Comment by Dqu1J** [comment]
Please don't create issues about updating to newer versions. I'm working on it, and am trying to get it to work asap.
