### ISSUE TITLE
People can use any command without login in 1.19

### ISSUE THREAD

**Issue by JoinChang** [Additional-Mods/simplerauth#45]
**Describe the bug**
People can use any command without login in 1.19

**To Reproduce**
- Connect to the server
- Type any other command without /login, such as /op

**Expected behavior**
Return unauthorized.

**Screenshots**
![image](https://user-images.githubusercontent.com/35451392/175483673-f477e469-f4f7-4ed4-b7df-89d64f965aa5.png)

**Version**
Mod version: 1.6.0
Minecraft version: 1.19
Fabric version: 0.55.3

**Additional context**
Same as other plugin: https://github.com/NikitaCartes/EasyAuth/issues/52

**Comment by AchalS-iglu** [comment]
same issue!
